from model.random_forrest import RandomStructuredRandomForrest
from model.encoder_decoder import EncoderDecoder
from model.patch_work import PatchWork
from model.pyramid_boosting import PyramidBoosting
